version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: Drs1312!
      POSTGRES_DB: survey
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - database

  pgadmin:
    image: dpage/pgadmin4:6.21
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - database

  mailservice:
    build:
      context: ../mail-service/project
      dockerfile: Dockerfile
    container_name: mailservice_container
    restart: always
    ports:
      - "5569:8080"
    networks:
      - database

volumes:
  postgres_data:
  pgadmin_data:

networks:
  database:
    driver: bridge
