name: Deploy Email Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/mailservice:latest ./mail-service/project

    - name: Push Docker image
      run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/mailservice:latest

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_DEPLOYER }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.APP_NAME_EMAIL_SERVICE }}
        images: ${{ secrets.ACR_LOGIN_SERVER }}/mailservice:latest