name: Build and deploy Python app to Azure Web App - prod-drs-be

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd backend/api
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Procfile
        run: |
          echo 'web: gunicorn --bind=0.0.0.0:$PORT --timeout 600 run:app --log-file -' > backend/api/Procfile

      - name: Zip artifact for deployment
        run: |
          cd backend/api
          zip -r ../../release.zip ./* -x ".env" "__pycache__/*" "*.pyc"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d ./deploy

      - name: List Deployment Package Contents
        run: |
          echo "Listing contents of the repo root"
          ls -la
          echo "Listing contents of backend/api"
          ls -la ./backend/api || echo "backend/api directory not found"
          echo "Listing contents of deploy directory:"
          ls -la ./deploy

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4C8B90EC3B444213A236FBF065BF8ADA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EE51CC1D9A9A4B70B995ED4DCD3A82F7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D47B7210775C4D7E810C30BCD251F3D4 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'prod-drs-be'
          slot-name: 'Production'
          package: './deploy'
